<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.myplayplanet.permission</groupId>
        <artifactId>PermissionSystem</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>permission-system-client</artifactId>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version> <!-- Match the version from the parent POM -->
                <configuration>
                    <skip>true</skip> <!-- Skip the resources goal -->
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>clone-openapi-templates</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>git</executable>
                            <arguments>
                                <argument>clone</argument>
                                <argument>https://github.com/Entjic/java-client-template.git</argument>
                                <argument>${project.build.directory}/openapi-templates/</argument>
                            </arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.11.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- <configHelp>true</configHelp> use this to print options-->

                            <!-- URL to your Swagger/OpenAPI spec -->
                            <enablePostProcessFile>true</enablePostProcessFile>
                            <inputSpec>
                                ${project.parent.basedir}/permission-system-service/target/generated/openapi.json
                            </inputSpec>
                            <generatorName>java</generatorName>
                            <apiPackage>net.myplayplanet.permission.api</apiPackage>
                            <modelPackage>net.myplayplanet.permission.model</modelPackage>
                            <invokerPackage>net.myplayplanet.permission.internal</invokerPackage>
                            <packageName>net.myplayplanet.permission</packageName>
                            <groupId>net.myplayplanet.permission</groupId>
                            <artifactId>permission-client</artifactId>
                            <configOptions>
                                <asyncNative>true</asyncNative>
                                <useJakartaEe>true</useJakartaEe>
                                <developerEmail>dev@myplayplanet.net</developerEmail>
                                <developerOrganization>MyPlayPlanet</developerOrganization>
                                <developerOrganizationUrl>myplayplanet.net</developerOrganizationUrl>
                            </configOptions>
                            <additionalProperties>
                                marker=IPermissionClient,markerPath=net.myplayplanet.permission.client.IPermissionClient,baseUrl=permissionServiceBaseUrl
                            </additionalProperties>
                            <templateDirectory>${project.build.directory}/openapi-templates/template</templateDirectory>
                            <library>webclient</library>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <apiNameSuffix>Client</apiNameSuffix>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.17.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
            <scope>provided</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.openapitools/jackson-databind-nullable -->
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/jakarta.ws.rs/jakarta.ws.rs-api -->
        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>net.myplayplanet.di</groupId>
            <artifactId>dependency-injector</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <!--Dark magic to ensure service gets build before client to ensure openapi.json already is generated!-->
        <dependency>
            <groupId>net.myplayplanet.permission</groupId>
            <artifactId>permission-system-service</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>