<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.myplayplanet.permission</groupId>
        <artifactId>PermissionSystem</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>permission-system-bukkit</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.javadoc.skip>true</maven.javadoc.skip>
        <version.inventory-api>2.0.2-SNAPSHOT</version.inventory-api>

    </properties>

    <dependencies>

        <dependency>
            <groupId>net.myplayplanet.permission</groupId>
            <artifactId>permission-system-generated-client</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.myplayplanet</groupId>
            <artifactId>inventory-api</artifactId>
            <version>${version.inventory-api}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.myplayplanet.messaging</groupId>
            <artifactId>messaging-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.myplayplanet.di</groupId>
            <artifactId>dependency-injector</artifactId>
            <version>1.0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.myplayplanet</groupId>
            <artifactId>player-client</artifactId>
            <version>3.0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.myplayplanet</groupId>
                <artifactId>myplayplanet-minecraft</artifactId>
                <version>3.0.4-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


</project>