spring.datasource.url=jdbc:mariadb://mysql_player:3306/mpp_permission?serverTimezone=Europe/Berlin
spring.datasource.username=paul
spring.datasource.password=
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
spring.sql.init.mode=always
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
