spring.datasource.url=jdbc:mariadb://mariadb:3306/permission?serverTimezone=Europe/Berlin
spring.datasource.username=paul
spring.datasource.password=admin
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
server.error.include-message=always
spring.sql.init.mode=always